### ISSUE TITLE
Nova pergunta;

### ISSUE THREAD

**Issue by pedrol8** [KingRider/lyceum-of-wisdom#5]
a torre jin mao de xangai tem quantos andares? 
R: 88

**Comment by pedrol8** [comment]
qual civilização fornece cura?
R: França

**Comment by pedrol8** [comment]
quem foi o professor de platão?

R: Socrates

**Comment by pedrol8** [comment]
qual [e o apelido de cleopatra vii no jogo? 

R: rainha do egito

**Comment by KingRider** [comment]
> qual civilização fornece cura? R: França

Pergunta errada não? ... correto é "Qual dessas civilizações pode aumentar sua velocidade de cura?"

Importante a pergunta certa para publicar.

Obrigado pela ajuda!

**Comment by pedrogiampietro** [comment]
@KingRider  Acho que é, não lembro bem, uiahuiahua, desenvolvi agora para ajudar:

https://lyceum-of-wisdom.vercel.app/

usei suas perguntas como banco de dados! espero que não se importe.

**Comment by KingRider** [comment]
![image](https://user-images.githubusercontent.com/4491180/162450746-14806112-6d93-4cac-ba1d-e97e73aec114.png)

Legal o site e inglês? baixou pacote de grátis rss

**Comment by pedrol8** [comment]
aaa pergunta aí, uihauihaui, vou atualizar aqui.
Ele tem ENG e PTBR, ele pega a versão que ta no idioma do navegador.

**Comment by pedrol8** [comment]
Que informação o item Tropas Enganosas falsifica para Batedores inimigos?
R: Contagem de unidades da sua cidade

**Comment by atqjunior** [comment]
Qual é a maior cidade do Reino Unido?
Resposta: Londres

**Comment by atqjunior** [comment]
Qual é a maior cidade do Reino Unido?
Resposta: Londres

**Comment by pedrol8** [comment]
A sua Prefeitura precisa estar em que nível para entrar na Idade do Ferro? 
R: 10

**Comment by KingRider** [comment]
> A sua Prefeitura precisa estar em que nível para entrar na Idade do Ferro? R: 10

Já existe a questão 463!

Obrigado atribuir.

**Comment by pedrogiampietro** [comment]
{
    "question": "Onde ocorreu a batalha final entre o Rei Arthur e Mordred, de acordo com a lenda arturiana?",
    "answer": "Camlann"
  },
  {
    "question": "Qual desses comandantes tem a capacidade de converter algumas unidades mortas em unidades gravemente ferias ao atacar uma cidade?",
    "answer": "Carlos Magno"
  },
  {
    "question": "Quantas vezes você pode receber uma ajuda da aliança se o seu centro de aliança estiver no nível 25?",
    "answer": "30"
  },
  {
    "question": "O famoso arqueólogo dinamarquês Christian Jurgensen Thomsen propôs o sistema de 'três idades' para categorizar a história antiga. Qual é a primeira etapa?",
    "answer": "Idade da Pedra"
  },
  {
    "question": "Qual destes eventos NÁO faz parte dos Jogos Olímpicos?",
    "answer": "Automobilismo"
  },
  {
    "question": "Um 'dia' no planeta Vênus é aproximadamente igual a quantos dias na Terra?",
    "answer": "243 dias"
  }

**Comment by KingRider** [comment]
5 perguntas é obrigado atribuindo!

**Comment by FrancyneYume** [comment]
O Colosso de Rodes representa qual deus do sol?
R: Helio
A "Marcha da Independencia" e o hino nacional de qual pais?
R:Turquia
Diego Velazquez, o pintor da obra realista Retrato do Papa Inocencio X, era de qual pais?

R: Espanha
Qual dos seguintes e o irmao mais velho de Zeus na mitologia grega?

R: Poseidon 
O Lago General Carrera se origina nas geleiras dos Andes. Quais sao os dois paises que fazem fronteira com o lago?

R: Argentina e Chile
Quem era o deus grego e tracio do vinho?

R: Dioniso
Quem foi o pai do rei franco Pepino, o Breve?

R: Carlos Martel
Onde nasceu o compositor Wolfgang Amadeus Mozart?

R: Salzburgo

**Comment by KingRider** [comment]
Obrigado Francyne 👍 está adicionado 7 novas perguntas e a outra pergunta "velho de Zeus" que já existe!

**Comment by FrancyneYume** [comment]
Disponha 😁👍

A casa de leiloes Sotheby’s foi fundada em 1744 em qual cidade inglesa?
R:Londres

Qual é a maior cordilheira continental da Terra?
R: Os Andes

Qual filme ganhou Melhor Filme no primeiro Oscar?
R: Asas

**Comment by FrancyneYume** [comment]
Na mitologia grega, qual herói montou o cavalo voador pegaso?
R: Belerofonte

O épico grego A Odisseia narra o retorno do herói Ulisses da guerra. Onde era sua terra natal?
R: Itaca

Qual a cor da vela que Teseu usou em seu navio para indicar a seu pai, Egeu, que havia matado com sucesso o Minotauro?
R: Branco

O periodo apos a queda da civilizacao micenica e antes do nascimento das cidades-estado gregas e conhecido como Idade das Trevas grega. Qual dessas obras foi escrita nessa epoca?
R: A Odisseia

Na Grecia antiga, quem era a alta sacerdotiza do Templo de Apolo em Delfos?
R: a Pitia

Qual desses antigos filosofos gregos NAO participou da discussao sobre justica na Republica de Platao?
R: Polemarco

Qual destas opcoes representa um dos quatro elementos fundamentais da natureza de acordo com muitos filosofos gregos antigos?
R: Vento

Qual filosofo criou o “ paradoxo da flecha “?
R: Zenao de Eleia

Quem saiu vencedor da “Batalha de Hastings” ?
R: Guilherme, o Conquistador

Qual capitulo das Cronicas do Reino concede a conquista “Explorador Eterno” caso toda a nevoa seja explorada antes do fim do capitulo?
R: A Longa Paz

Qual a montanha mais alta da Africa?
R: Monte Kilimajaro

**Comment by KingRider** [comment]
Atribuir 5 é obrigado Francine

**Comment by FrancyneYume** [comment]
Qual destas foi a primeira estacao espacial do mundo?
R: Salyut 1

Muitas figuras historicas lutaram na terceira cruzada, Qual dos lideres abaixo morreu neste movimento militar?
R: Frederico Barba Ruiva

Qual dos metodos a seguir NAO  aumentara a velocidade de pesquisa da sua academia?
R: Tornar-se a Justica do seu reino

No Rok, qual tecnologia e pre-requisito para a tecnologia militar fitoterapia?
R: Camuflagem

**Comment by KingRider** [comment]
Obrigado Francine está atualizado com sucesso.

**Comment by FrancyneYume** [comment]
No evento O Governador Mais Poderoso, qual e a classificação mínima que você precisa alcançar para receber 10 esculturas de comandante do evento?
R: 15ª

Qual dos seguintes impérios NÃO participou da Batalha dos Três Imperadores (também conhecida como Batalha de Austerlitz)?
R: O Império Persa

Quem e o deus hindu da destruição, também conhecido como ‘’dançarino cósmico’’)?
R: Shiva

**Comment by FrancyneYume** [comment]
NA MITOLOGIA NORDICA, A QUEM PERTENCE O MARTELO MJOLNIR?
R: THOR

QUAL DESSE GRUPOS ETNICOS CHINESES É CONHECIDO POR BEBER KUMIS, UMA BEBIDA FEITA COM LEITE DE EGUA FERMENTADO?
R: MONGOIS

**Comment by FrancyneYume** [comment]
Qual dessas obras não se passa durante a Guerra de Tróia?
R: Antígona

Em que continente está localizado Benin?
R: África

Qual das seguintes frutas, conhecida como "pera do lobo", imaginou-se erroneamente ser venenosa?
R: Tomate

Qual das histórias a seguir não faz parte dos Contos de Fadas dos irmãos Grimm?
R: A pequena sereia

Quem era responsável por conduzir bravos guerreiros ao Valhalla após a morte na mitologia nórdica?
R:Valquírias

**Comment by FrancyneYume** [comment]
Em que pais nasceu Botticelli, pintor de O Nascimento de Venus?
R: Italia

Qual dessas cidades NAO fica na Asia?
R: Melbourne

Li Xin, o ancestral do “General Voador” Li Guang, era um general de qual estado durante o periodo do Reinos Combatentes da historia chinesa?
R: Qin

Dentre as fossas oceanicas conhecidas, qual e a mais profunda do mundo?
R: A Fossa das Marianas

Qual foi o único presidente dos Estados Unidos que serviu mais do que dois mandatos?
R: Franklin D. Roosevelt

**Comment by FrancyneYume** [comment]
Em Rok, qual e a cor da bainha de Matilda de Flanders?
R: Azul
Em que pais o misterioso Stonehenge esta localizado?
R: Reino Unido
Como e chamada a habilidade de especializacao do comandante Cao Cao?
R: Imperador Wu de Wei 
Quem ordenou a producao do manuscrito civil popularmente conhecido como Livro do Juizo Final?
R: Guilherme I

**Comment by KingRider** [comment]
raolpi29 me mandou mensagem e a mesma sua pergunta e acabei atualizando.

Eu não participei do exame intermediário de hoje (25/Novembro) e estou doente mal (temporal), muito obrigado!

____________________________________________
*Sandro Alvares (KingRider)*
***@***.***
*Skype:* live:*sandro.alvares*
*Battle.NET: KingRider#1398*
*Discord: KingRider**#2541*


Em sáb., 25 de nov. de 2023 às 09:49, FrancyneYume ***@***.***>
escreveu:

**Comment by FrancyneYume** [comment]
O Mar de Aral já foi o quarto maior lago do mundo, mas desde entao praticamente secou. Onde ele esta localizado?
R: Asia Central
Qual destas e uma descricao incorreta da “Batalha de Poitiers”?
R: A campanha aconteceu durante a Primeira Guerra Mundial
Na mitologia grega, qual juiz dos mortos era responsavel por dar o voto decisivo em todas as almas?
R: Minos

*esta foi da semana passada se não me engano. Esqueci de postar XD

**Comment by FrancyneYume** [comment]
esta foi da semana passada se não me engano. Esqueci de postar XD

**Comment by FrancyneYume** [comment]
Uma cratera no outro lado da Lua recebeu o nome de um oficial chines que foi (supostamente) a primeira pessoa a viajar para o espaco. Qual era o nome dele?
R: Wan Hu
Qual dos seguintes seres vivos são carnivoros?
R: Libélulas
* Todas as "pendencias" que acumulei foram postadas =D
* Espero que você melhore logo =(

**Comment by FrancyneYume** [comment]
Qual dos seguintes animais estava na bandeira imperial do Imperio Inca?
R: Cobra
Qual foi o primeiro filme dirigido por Satoshi Kon?
R: Perfect Blue
Durante a fusao nuclear, qual dos seguintes elementos produz menos energia do que absorve?
R: Ferro
Qual dos seguintes treinadores levou seu time a 13 titulos da Liga de Futebol Inglesa?
R: Alex Ferguson
Em que continente estava localizado o Imperio Inca?
R: America do Sul

*Exame Final

**Comment by KingRider** [comment]
Obrigado Francyne Yume

**Comment by FrancyneYume** [comment]
No xadrez internacional, qual lado se move primeiro?
R: Branco
Na revista em quadrinhos “Batman”, da DC Comics, qual versão de Robin morreu por conta de uma votação dos leitores?
R: Jason Todd (capuz Vermelho)

**Comment by KingRider** [comment]
Obrigado Yume

**Comment by FrancyneYume** [comment]
Qual é o aumento na Velocidade de Coleta quando os membros da aliança coletam recursos no território da aliança?
R: 25%

Qual das seguintes equipes foi a primeira a marcar 100 pontos em uma única temporada da Liga de Futebol Inglesa?
R: Manchester City

**Comment by FrancyneYume** [comment]
Qual destas frutas NAO cresce em arvores?
R: Morango 
Em RoK, qual comandante  é apelidado de ``Rainha de Silla’’?
R: Seondeok

A qual exercito pertencia a ``Guarda Varangiana”?
R: O exercito bizantino

A conquista otomana de Constantinopla em 1453 marcou o fim do Império Romano do Oriente. Quem era o imperador romano na época?
R: Constantino XI Paleologo

Qual é a duração do item de Recrutamento de Construtor?
R: 2 dias

Qual  é o maior lago da Europa?
R: Lago Ladoga.

Quem foi o primeiro autor japonês a receber o Premio Nobel de Literatura?
R: Yasunari Kawabata

**Comment by FrancyneYume** [comment]
A ametista e valorizada por sua tonalidade violeta brilhante. De que mineral ela e uma variedade?
R: Quartzo

Qual e o maior aeroporto do mundo em area?
R: Aeroporto Internacional King Fahd

**Comment by FrancyneYume** [comment]
Quem fundou a Ordem da Jarreteira da Inglaterra?
R: Eduardo III

Qual destas afirmações sobre o titulo ‘’tribuna da plebe’’ esta incorreta?
R: Eles eram totalmente subservientes ao Senado

**Comment by FrancyneYume** [comment]
Quem sucedeu a Pedro I como imperador da Russia?
R: Catherine I
Na mitologia grega, qual era o nome do rei que transformava em ouro tudo o que tocava?
 R: Midas
A bandeira de qual desses paises contem o maior numero de cores?
 R: Republica da Coreia
O alfabeto gotico foi desenvolvido por qual bispo?
 R: Ulfilas
Quem escreveu “A Eneida”, o primeiro poema epico da literatura ocidental?
 R: Virgilio
Qual das seguintes marcas forneceu a bola oficial da Liga de Futebol Inglesa antes de 2000?
 R: Mitre
Quem reunificou a China e encerrou o periodo das Dinastias do Norte e do Sul da historia chinesa?
 R: Imperador Wen do Sui
Em que idioma foi escrito o Nibelungenlied?
 R: Alto-alemão medio
Em que museu esta atualmente a pintura “A Coroacão de Napoleao” ?
 R: Louvre
Qual imperador romano derrotou e capturou Zenobia?
 R: Aureliano
No Rok, qual dos seguintes comandantes carrega um escudo?
R: Hermann
Qual dos seguintes animais NÃO esta extinto?
R: Panda gigante
Em 2024, qual destas construcoes ainda NÃO foi concluida?
R: Sagrada Familia
Qual dos seguintes e um numero primo?
R: 29
Que filosofo cunhou o termo filosofico “entelequia”?
R: Aristoteles
Quem foi o diretor do jogo premiado como Jogo do Ano no Game Awards 2022?
R: Hidetaka Miyazaki

**Comment by KingRider** [comment]
Obrigado Francyne
